[package]
name = "sketches"
version = "0.1.1"
edition = "2024"
autobins = false
description = "Probabilistic data structures for scalable approximate analytics"
license = "MIT"
readme = "README.md"

[dependencies]
